import "server-only";

import type { InvoiceStatus } from "@/features/invoices/invoice.types";
import type { CustomerId, InvoiceId } from "@/lib/definitions/brands";

/**
 * Domain model for Invoice.
 * Used for database and server logic.
 * All fields are strictly typed and immutable.
 * @remarks
 * Contains `id` as it represents the primary key in the database.
 */
export interface InvoiceEntity {
  readonly amount: number; // amount in cents
  readonly customerId: CustomerId; // branded type
  readonly date: string; // date in ISO format (YYYY-MM-DD)
  readonly id: InvoiceId; // branded type
  readonly sensitiveData: string; // sensitive data for internal use
  readonly status: InvoiceStatus; // status of the invoice (pending, paid)
}

/**
 * Domain model for creating a new invoice.
 * All fields are strictly typed and immutable.
 * @exclude `id` as it is generated by the database.
 */
export type InvoiceFormEntity = Omit<InvoiceEntity, "id">;

/**
 * Partial domain model for updating an invoice.
 * All fields are optional to allow partial updates.
 * Used in update operations where not all fields need to be provided.
 */
export type InvoiceFormPartialEntity = Partial<InvoiceFormEntity>;
