import "server-only";

import type { RevenueId } from "@/lib/definitions/brands";

/**
 * Represents a revenue entity in the database, defining the structure and properties of a revenue record.
 * @remarks The most important column will be `period` which is a combination of `year` and `month` (ex. 2024-01).
 */
export interface RevenueEntity {
  readonly calculationSource: string; // 'seed' or 'handler' or 'rolling_calculation'
  readonly createdAt: Date;
  readonly id: RevenueId;
  readonly invoiceCount: number; // Number of invoices associated with this revenue record
  readonly period: string; // Combination of year and month (ex. 2024-01)
  readonly revenue: number; // Revenue amount for period in cents
  readonly updatedAt: Date;
}

/**
 * Domain model for creating a new revenue record.
 * @exclude `id` as it is auto-generated by the database.
 */
export type RevenueCreateEntity = Omit<RevenueEntity, "id">;

/**
 * Partial domain model for updating a revenue record. All fields are optional to allow partial updates.
 */
export type RevenuePartialEntity = Partial<RevenueCreateEntity>;
