import "server-only";

import { isValid } from "date-fns";
import type {
  InvoiceEntity,
  InvoiceFormEntity,
  InvoiceServiceEntity,
} from "@/modules/invoices/domain/invoice.entity";
import { validateInvoiceStatus } from "@/modules/invoices/domain/invoice-status.validator";
import type { InvoiceRow } from "@/server/db/schema/invoices";
import {
  toCustomerId,
  toInvoiceId,
  toPeriod,
} from "@/shared/branding/converters/id-converters";
import type { AppError } from "@/shared/errors/core/app-error.entity";
import { makeAppError } from "@/shared/errors/factories/app-error.factory";
import { Err, Ok } from "@/shared/result/result";
import type { Result } from "@/shared/result/result.types";

/**
 * Converts a date to the first day of the same month.
 * @param date - The input date
 * @returns A new Date object representing the first day of the month
 */
function toFirstDayOfMonthLocal(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth(), 1);
}

/**
 * Maps raw database row to branded Entity.
 */
export function rawDbToInvoiceEntity(
  row: InvoiceRow,
): Result<InvoiceEntity, AppError> {
  const statusResult = validateInvoiceStatus(row.status);
  if (!statusResult.ok) {
    return Err(statusResult.error);
  }

  return Ok({
    amount: row.amount,
    customerId: toCustomerId(row.customerId),
    date: row.date,
    id: toInvoiceId(row.id),
    revenuePeriod: toPeriod(row.revenuePeriod),
    sensitiveData: row.sensitiveData,
    status: statusResult.value,
  });
}

/**
 * Maps branded InvoiceFormEntity to InvoiceServiceEntity.
 * Used for service layer operations.
 * @exclude
 * Excludes `id` since IDs are generated by the database.
 * @param formEntity - `InvoiceFormEntity` Branded form entity with valid Date object
 */
export function invoiceFormEntityToServiceEntity(
  formEntity: InvoiceFormEntity,
): Result<InvoiceServiceEntity, AppError> {
  if (!isValid(formEntity.date)) {
    return Err(
      makeAppError("validation", {
        cause: "",
        message: `Invalid date in form entity: ${formEntity.date}`,
        metadata: {},
      }),
    );
  }

  const derivedRevenuePeriod = toFirstDayOfMonthLocal(formEntity.date);

  return Ok({
    ...formEntity,
    revenuePeriod: toPeriod(derivedRevenuePeriod),
  });
}
