# version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /project
    volumes:
      - .:/project
      - /project/node_modules
    ports:
      - "3000:3000"
      - "9230:9230"
    command: npm run dev
    env_file:
      - .env
    environment:
      DUMB_VARIABLE: "dumb value"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      DUMB_VARIABLE: "dumb value"


volumes:
  postgres-data:
