services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /project
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - .:/project:cached # Source code with performance optimization
      - node_modules:/project/node_modules:delegated # Named volume for node_modules
      - pnpm-store:/pnpm/store:delegated # Named volume for pnpm store
    environment:
      NODE_ENV: development
      #      NODE_OPTIONS: --inspect=0.0.0.0:9229
      SESSION_SECRET_FILE: /run/secrets/session_secret
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_URL_FILE: /run/secrets/postgres_url
      POSTGRES_TESTDB_URL_FILE: /run/secrets/postgres_testdb_url
      POSTGRES_TESTDB_PASSWORD_FILE: /run/secrets/postgres_testdb_password
      NEXT_TELEMETRY_DISABLED: 1
    entrypoint: ["/bin/sh", "/project/entrypoint.sh"]
    command: ["pnpm", "dev"]
    depends_on:
      db:
        condition: service_healthy
    user: "node"
    secrets:
      - session_secret
      - postgres_password
      - postgres_testdb_url
      - postgres_url
      - postgres_testdb_password
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5

  # --- E2E web service (uses test DB, but NODE_ENV=development for Next.js) ---
  web-e2e:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /project
    ports:
      - "3001:3000" # Avoid port clash with dev web
    volumes:
      - .:/project:cached
      - node_modules:/project/node_modules:delegated
      - pnpm-store:/pnpm/store:delegated
    environment:
      NODE_ENV: development # Must be 'development' for Next.js
      SESSION_SECRET_FILE: /run/secrets/session_secret
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_testdb_password
      POSTGRES_URL_FILE: /run/secrets/postgres_testdb_url
      POSTGRES_TESTDB_URL_FILE: /run/secrets/postgres_testdb_url
      POSTGRES_TESTDB_PASSWORD_FILE: /run/secrets/postgres_testdb_password
      NEXT_TELEMETRY_DISABLED: 1
      # Optionally, add a custom variable to distinguish test env
      E2E: "true"
    entrypoint: ["/bin/sh", "/project/entrypoint.sh"]
    command: ["pnpm", "dev"]
    depends_on:
      testDB:
        condition: service_healthy
    user: "node"
    secrets:
      - session_secret
      - postgres_testdb_password
      - postgres_testdb_url
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
    profiles: ["e2e"]

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Host port 5432 -> Container port 5432
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    secrets:
      - postgres_password
    networks:
      - dashboard-network

  testDB:
    image: postgres:latest
    volumes:
      - testDB-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Host port 5433 -> Container port 5432
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_testdb_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    secrets:
      - postgres_testdb_password
    networks:
      - dashboard-network

  cypress:
    image: cypress/included:14.3.3 # Match your Cypress version
    working_dir: /e2e
    volumes:
      - .:/e2e
      - node_modules:/e2e/node_modules
    environment:
      NODE_ENV: development
      SESSION_SECRET_FILE: /run/secrets/session_secret
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_testdb_password
      POSTGRES_URL_FILE: /run/secrets/postgres_testdb_url
      POSTGRES_TESTDB_PASSWORD_FILE: /run/secrets/postgres_testdb_password
      POSTGRES_TESTDB_URL_FILE: /run/secrets/postgres_testdb_url
      NEXT_TELEMETRY_DISABLED: 1
      CYPRESS_baseUrl: http://web-e2e:3000
    depends_on:
      web-e2e:
        condition: service_healthy
      testDB:
        condition: service_healthy
      adminer:
        condition: service_healthy
    secrets:
      - session_secret
      - postgres_testdb_password
      - postgres_testdb_url
    networks:
      - dashboard-network
    entrypoint: ["/bin/sh", "-c"]
    command: ["npx cypress run --e2e --spec cypress/e2e/auth/signup.cy.ts"]
    profiles: ["e2e"]

    # run with
    # docker compose -f compose.dev.yaml --profile e2e up --build web-e2e cypress

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: flat
    networks:
      - dashboard-network
    depends_on:
      - db
      - testDB
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db-data:
  testDB-data:
  node_modules:
  pnpm-store:

secrets:
  session_secret:
    file: ./secrets/session_secret.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_url:
    file: ./secrets/postgres_url.txt
  postgres_testdb_url:
    file: ./secrets/postgres_testdb_url.txt
  postgres_testdb_password:
    file: ./secrets/postgres_testdb_password.txt

networks:
  dashboard-network:

# Example connection URLs:

# From host:
#   db:     postgres://user:password@localhost:5432/database
#   testDB: postgres://user:password@localhost:5433/database

# From another container:
#   db:     postgres://user:password@db:5432/database
#   testDB: postgres://user:password@testDB:5432/database

# NOTE:
# - Use postgres://user:password@db:5432/database for services running inside Docker (e.g., web service).
# - Use postgres://user:password@localhost:5432/database for local development outside Docker.
# - Set your Docker secrets accordingly for each environment.

# TIP:
# Always run Drizzle schema/migration commands inside the 'web' container
# to ensure correct database connectivity (use: db as hostname).
