services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.prod
    working_dir: /app
    volumes:
      - .:/app:cached
      - prod_node_modules:/app/node_modules:delegated
      - prod_pnpm-store:/pnpm/store:delegated
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      SESSION_SECRET_FILE: /run/secrets/session_secret
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_URL_FILE: /run/secrets/postgres_url
    secrets:
      - session_secret
      - postgres_password
      - postgres_url
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: password
      # POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    secrets:
      - postgres_password
    volumes:
      - nextjs_dashboard_prod_data:/var/lib/postgresql/data
    networks:
      - my_network

  cron:
    image: alpine/curl
    command: >
      sh -c "
        echo '*/10 * * * * curl -X POST http://web:3000/db/clear' > /etc/crontabs/root && \
        crond -f -l 2
      "
    depends_on:
      - web
    networks:
      - my_network

volumes:
  nextjs_dashboard_prod_data:
  prod_node_modules:
  prod_pnpm-store:


secrets:
  session_secret:
    file: ./secrets/session_secret
  postgres_password:
    file: ./secrets/postgres_password
  postgres_url:
    file: ./secrets/postgres_url

networks:
  my_network:
    name: my_network
    driver: bridge
