services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /project
    ports:
      - "3000:3000"
      - "9229:9229"
    # post_start:
      # - command: "npx drizzle-kit push --config drizzle.config.ts"
    volumes:
      - .:/project
      - /project/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
      NODE_OPTIONS: --inspect=0.0.0.0:9229
      SESSION_SECRET_FILE: /run/secrets/session_secret
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_URL_FILE: /run/secrets/postgres_url
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT_FILE: /run/secrets/postgres_port
      POSTGRES_USER: ${POSTGRES_USER}
    entrypoint: ["/bin/sh", "/project/docker-entrypoint.sh"]
    command: ["npm", "run", "dev"]
    depends_on:
      - postgres
    user: "node"
    secrets:
      - session_secret
      - postgres_db
      - postgres_password
      - postgres_url
      - postgres_port
    networks:
      - dashboard-network

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
    user: "postgres"
    networks:
      - dashboard-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    user: "pgadmin"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - dashboard-network

volumes:
  postgres-data:
  pgadmin-data:

secrets:
  session_secret:
    file: ./secrets/session_secret.txt
  postgres_db:
    file: ./secrets/postgres_db.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_url:
    file: ./secrets/postgres_url.txt
  postgres_port:
    file: ./secrets/postgres_port.txt

networks:
  dashboard-network: