services:

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /project
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/project
      - /project/node_modules
    env_file:
      - .env
    environment:
       NODE_ENV: development
       NODE_OPTIONS: --inspect=0.0.0.0:9229
    command: npm run dev
    depends_on:
      - postgres
    user: "myuser"
    secrets:
      - connection_string
      - db_password

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    secrets:
      - db_password
      - connection_string

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    secrets:
      - db_password
      - connection_string

volumes:
  postgres-data:

secrets:
  db_password:
    file: ./secrets/db_password.txt
  connection_string:
    file: ./secrets/connection_string.txt
