services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /project
    ports:
      - "3000:3000"
      - "9229:9229"
      # post_start:
      # - command: "npx drizzle-kit push --config drizzle.config.ts"
    volumes:
      - .:/project
    environment:
      NODE_ENV: development
      NODE_OPTIONS: --inspect=0.0.0.0:9229
      SESSION_SECRET_FILE: /run/secrets/session_secret
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_URL_FILE: /run/secrets/postgres_url
    entrypoint: [ "/bin/sh", "/project/entrypoint.sh" ]
    command: [ "npm", "run", "dev" ]
    depends_on:
      - db
    user: "node"
    secrets:
      - session_secret
      - postgres_password
      - postgres_url
    networks:
      - dashboard-network

  #  run with docker compose -f compose.dev.yaml run testing-web
  # testing-web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   working_dir: /project
  #   volumes:
  #     - .:/project
  #   environment:
  #     NODE_ENV: test
  #     SESSION_SECRET_FILE: /run/secrets/session_secret
  #     POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
  #     POSTGRES_URL_FILE: /run/secrets/postgres_url
  #   entrypoint: [ "/bin/sh", "/project/entrypoint.sh" ]
  #   command: [ "npm", "run", "test" ]
  #   depends_on:
  #     - db
  #   user: "node"
  #   secrets:
  #     - session_secret
  #     - postgres_password
  #     - postgres_url
  #   networks:
  #     - dashboard-network

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    networks:
      - dashboard-network

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - dashboard-network
    depends_on:
      - web

volumes:
  db-data:

    # profiles:
    #   testing:
    #     services:
    #       web:
    #         environment:
    #           NODE_ENV: test
    #           SESSION_SECRET_FILE: /run/secrets/session_secret
    #           POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    #           POSTGRES_URL_FILE: /run/secrets/postgres_url
    #         entrypoint: [ "/bin/sh", "/project/entrypoint.sh" ]
    #         command: [ "npm", "run", "test" ]


secrets:
  session_secret:
    file: ./secrets/session_secret.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_url:
    file: ./secrets/postgres_url.txt

networks:
  dashboard-network:
