services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /project
    ports:
      - "3000:3000" # Next.js application
      - "9229:9229" # Node.js inspector for debugging
      - "9230:9230" # Additional debug port for tests
    volumes:
      - .:/project:cached # Source code with performance optimization
      - node_modules:/project/node_modules:delegated # Named volume for node_modules
      - pnpm-store:/pnpm/store:delegated # Named volume for pnpm store
    environment:
      NODE_ENV: development
      #      NODE_OPTIONS: --inspect=0.0.0.0:9229
      SESSION_SECRET_FILE: /run/secrets/session_secret
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_URL_FILE: /run/secrets/postgres_url
      NEXT_TELEMETRY_DISABLED: 1 # Disable telemetry
    entrypoint: ["/bin/sh", "/project/entrypoint.sh"]
    command: ["pnpm", "dev"]
    depends_on:
      db:
        condition: service_healthy
    user: "node"
    secrets:
      - session_secret
      - postgres_password
      - postgres_url
    networks:
      - dashboard-network

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    #      POSTGRES_USER: postgres
    #      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    secrets:
      - postgres_password
    networks:
      - dashboard-network

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: flat # Use a cleaner design
    networks:
      - dashboard-network
    depends_on:
      - db

volumes:
  db-data:
  node_modules: # Named volume for node_modules
  pnpm-store: # Named volume for pnpm store

secrets:
  session_secret:
    file: ./secrets/session_secret.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_url:
    file: ./secrets/postgres_url.txt

networks:
  dashboard-network:
