packages:
  - .

allowBuilds:
  cypress: true
  dprint: true
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - cypress
  - dprint
  - esbuild
  - sharp

overrides:
  esbuild: ^0.25.0
  vite: ^7.3.5
  postcss: ^8.5.15

sideEffectsCache: false
