services:
  web-app:
    container_name: web-app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../.env
    volumes:
      - ../..:/workspaces:cached
    restart: "no"
    ports:
      - "3000:3000"
    networks:
      - my_network
    healthcheck:
      test: curl -f http://localhost:3000 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
    command: sleep infinity
    # network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  my_network:
    name: my_network
