services:
  node-server:
    container_name: node-server
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      postgres-db:
        condition: service_healthy
    env_file:
      - ../.env
    volumes:
      - ../:/project/nextjs-dashboard:cached
    restart: 'unless-stopped'
    ports:
      - '3000:3000'
    networks:
      - my_network
    healthcheck:
      test: curl -f http://localhost:3000 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
    command: sleep infinity
    # network_mode: service:postgres-db

  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - my_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-db-data:

networks:
  my_network:
    name: my_network
