/**
 * Configuration constants for seeding operations.
 */
export const SEED_CONFIG = {
  DEMO_COUNTER_MAX: 100,
  DEMO_COUNTER_MIN: 1,
  FIRST_DAY_OF_MONTH: 1,
  GENERATE_MONTHLY_PERIODS_COUNT: 19,
  INVOICE_COUNT: 70,
  INVOICE_REGULAR_THRESHOLD: 0.9,
  INVOICE_STATUS_PENDING_PROBABILITY: 0.5,
  LARGE_AMOUNT_THRESHOLD: 1_500_001,
  MAX_AMOUNT_CENTS: 1_500_000,
  MAX_LARGE_AMOUNT_CENTS: 5_000_000,
  MIN_AMOUNT_CENTS: 500,
  MIN_AMOUNT_PROBABILITY: 0.1,
  MIN_MONTH: 1,
  MONTHS_IN_YEAR: 12,
  SALT_ROUNDS: 10,
  SINGLE_CENT_AMOUNT: 1,
  SINGLE_CENT_PROBABILITY: 0.05,
  ZERO_AMOUNT_PROBABILITY: 0.05,
} as const;
