import "server-only";

import { toInvoiceStatus } from "@/features/invoices/lib/mappers";
import type { InvoiceRow } from "@/server/db/schema/invoices";
import type {
  InvoiceEntity,
  InvoiceFormEntity,
  InvoiceServiceEntity,
} from "@/server/invoices/entity";
import {
  toCustomerId,
  toInvoiceId,
  toPeriod,
} from "@/shared/branding/id-converters";
import { AppError } from "@/shared/errors/core/app-error.class";
import { Err, Ok } from "@/shared/result/result";
import type { Result } from "@/shared/result/result.types";
import { isDateValid } from "@/shared/utils/date/guards";
import { toFirstDayOfMonthLocal } from "@/shared/utils/date/normalize";

/**
 * Maps raw database row to branded Entity.
 */
export function rawDbToInvoiceEntity(
  row: InvoiceRow,
): Result<InvoiceEntity, AppError> {
  const statusResult = toInvoiceStatus(row.status);
  if (!statusResult.ok) {
    return Err(statusResult.error);
  }

  return Ok({
    amount: row.amount,
    customerId: toCustomerId(row.customerId),
    date: row.date,
    id: toInvoiceId(row.id),
    revenuePeriod: toPeriod(row.revenuePeriod),
    sensitiveData: row.sensitiveData,
    status: statusResult.value,
  });
}

/**
 * Maps branded InvoiceFormEntity to InvoiceServiceEntity.
 * Used for service layer operations.
 * @exclude
 * Excludes `id` since IDs are generated by the database.
 * @param formEntity - `InvoiceFormEntity` Branded form entity with valid Date object
 */
export function invoiceFormEntityToServiceEntity(
  formEntity: InvoiceFormEntity,
): Result<InvoiceServiceEntity, AppError> {
  if (!isDateValid(formEntity.date)) {
    return Err(
      new AppError("validation", {
        message: `Invalid date in form entity: ${formEntity.date}`,
      }),
    );
  }

  const derivedRevenuePeriod = toFirstDayOfMonthLocal(formEntity.date);

  return Ok({
    ...formEntity,
    revenuePeriod: toPeriod(derivedRevenuePeriod),
  });
}
